# Generated by Django 3.1.4 on 2020-12-24 07:09

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('camp', '0002_auto_20201224_1210'),
    ]

    operations = [
        migrations.CreateModel(
            name='Add',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('Country', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('zip_code', models.CharField(max_length=7)),
                ('added_by', models.ManyToManyField(related_name='added_place', through='camp.Add', to='camp.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='Visited',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visited_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='camp.place')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='camp.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('star_rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='camp.place')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='camp.customer')),
            ],
        ),
        migrations.AddField(
            model_name='place',
            name='rated_by',
            field=models.ManyToManyField(related_name='rated_place', through='camp.Rating', to='camp.Customer'),
        ),
        migrations.AddField(
            model_name='place',
            name='visited_by',
            field=models.ManyToManyField(related_name='visited_place', through='camp.Visited', to='camp.Customer'),
        ),
        migrations.AddField(
            model_name='add',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='camp.place'),
        ),
        migrations.AddField(
            model_name='add',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='camp.customer'),
        ),
    ]
