# Generated by Django 3.1.4 on 2020-12-24 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('camp', '0003_auto_20201224_1239'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='add',
            table='add',
        ),
        migrations.AlterModelTable(
            name='place',
            table='places',
        ),
        migrations.AlterModelTable(
            name='rating',
            table='rating',
        ),
        migrations.AlterModelTable(
            name='visited',
            table='visited',
        ),
    ]
