# Generated by Django 3.1.4 on 2020-12-24 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('camp', '0005_comment'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='comment',
            table='comment',
        ),
    ]
