# Generated by Django 3.1.4 on 2020-12-26 06:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('camp', '0006_auto_20201224_2237'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='place',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='camp.place'),
        ),
    ]
