# Generated by Django 3.1.4 on 2020-12-26 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('camp', '0009_place_image_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='place',
            old_name='image_url',
            new_name='place_url',
        ),
    ]
