# Generated by Django 3.1.4 on 2020-12-30 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('camp', '0013_comment_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='author',
        ),
    ]
