# Generated by Django 3.1.4 on 2021-01-10 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('camp', '0016_auto_20210101_2014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='places', to='camp.place'),
        ),
    ]
