# Generated by Django 3.1.4 on 2021-01-10 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camp', '0017_auto_20210110_2047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='star_rating',
            field=models.IntegerField(default=0),
        ),
        migrations.AddConstraint(
            model_name='rating',
            constraint=models.CheckConstraint(check=models.Q(('star_rating__gte', 1), ('star_rating__lte', 5)), name='rate between 1 and 5'),
        ),
    ]
